<?php

/**
 * @file
 * Code for the Farm Record module.
 */

include_once('farm_record.entity.inc');

/**
 * Implements hook_hook_info().
 */
function farm_record_hook_info() {
  $hooks['farm_record_types'] = array(
    'group' => 'farm_record',
  );
  return $hooks;
}

/**
 * Load farmOS record type information.
 *
 * @param string $entity_type
 *   Optionally specify the entity type.
 * @param string $bundle
 *   Optionally specify the entity bundle.
 *
 * @return array
 *   Returns an array of record type information. See farm_record.api.php.
 */
function farm_record_types($entity_type = '', $bundle = '') {

  // Ask modules for record type information and static cache the results.
  $record_types = &drupal_static(__FUNCTION__);
  if (!isset($record_types)) {
    $record_types = module_invoke_all('farm_record_types');
  }

  // If an entity type or bundle are provided, filter the results.
  if (!empty($entity_type) || !empty($bundle)) {

    // If there are no records of that entity type, return nothing.
    if (empty($record_types[$entity_type])) {
      return array();
    }

    // If bundle isn't specified, return all bundles of that entity type.
    if (empty($bundle)) {
      return $record_types[$entity_type];
    }

    // If the bundle doesn't exist, return nothing.
    if (empty($record_types[$entity_type][$bundle])) {
      return array();
    }

    // Return information about the specific bundle.
    return $record_types[$entity_type][$bundle];
  }

  // Otherwise return all information.
  return $record_types;
}

/**
 * Load farmOS record type information provided by a specific module.
 *
 * @param string $module
 *   The name of the module providing the record type information.
 *
 * @return array
 *   Returns an array of record type information. See farm_record.api.php.
 */
function farm_record_types_from_module($module) {

  // Define the hook.
  $hook = 'farm_record_types';

  // If the module does not implement the hook, return an empty array.
  if (!module_hook($module, $hook)) {
    return array();
  }

  // Invoke the hook and return the results.
  return module_invoke($module, $hook);
}
