<?php
/**
 * @file
 * Code for the Farm Water module.
 */

/**
 * Implements hook_farm_log_categories().
 */
function farm_water_farm_log_categories() {

  // Provide a "Water" log category.
  return array('Water');
}

/**
 * Implements hook_farm_lab_test_types().
 */
function farm_water_farm_lab_test_types() {

  // Provide a "Water test" lab test type.
  return array(
    'water' => t('Water test'),
  );
}
