<?php

/**
 * @file
 * Farm map Mapbox.
 */

/**
 * Implements hook_farm_info().
 */
function farm_map_mapbox_farm_info() {
  $info = array();

  // Add the Mapbox API key to /farm.json.
  $api_key = variable_get('farm_map_mapbox_api_key', '');
  if (!empty($api_key)) {
    $info['mapbox_api_key'] = $api_key;
  }

  return $info;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function farm_map_mapbox_form_farm_map_settings_form_alter(&$form, &$form_state, $form_id) {

  // Add a field for setting the Mapbox API key in the farm_map settings form.
  $form['farm_map_mapbox_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Mapbox API Key'),
    '#description' => t('Google Maps layers require that you obtain an API key. Refer to the <a href="@doc">Google Maps API Key</a> documentation on farmOS.org for instructions.', array('@doc' => 'https://farmos.org/hosting/googlemaps')),
    '#default_value' => variable_get('farm_map_mapbox_api_key', ''),
  );
}

/**
 * Implements hook_preprocess_farm_map().
 */
function farm_map_mapbox_preprocess_farm_map() {

  // If a Mapbox API key is set, enable Mapbox layers in farm maps.
  $api_key = variable_get('farm_map_mapbox_api_key', FALSE);
  if (!empty($api_key)) {

    // Add the API key as a JavaScript setting.
    $setting = array(
      'farm_map_mapbox' => array(
        'api_key' => $api_key,
      ),
    );
    drupal_add_js($setting, array('type' => 'setting'));

    // Add a farmOS map behavior that will add Mapbox layers.
    drupal_add_js(drupal_get_path('module', 'farm_map_mapbox') . '/farm_map_mapbox.js');
  }
}
