version: '2'
services:
  db:
    image: mariadb:latest
    volumes:
      - './db:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: farm
      MYSQL_DATABASE: farm
      MYSQL_USER: farm
      MYSQL_PASSWORD: farm
      # Enable this if your hard drive is not SSD.
#      MYSQL_INITDB_SKIP_TZINFO: 1 # @see https://github.com/docker-library/mariadb/issues/262

  www:
    depends_on:
      - db
    image: farmos/farmos:dev
    volumes:
      - './www:/var/www/html'
    ports:
      - '80:80'
    # On Linux, uncomment these lines and set the IP address to match the host.
#    environment:
#      XDEBUG_CONFIG: remote_host=172.17.0.1
