version: '3'
services:
  www:
    image: farmos/farmos:2.x-dev
    volumes:
      - './www:/opt/drupal'
    environment:
      FARMOS_FS_READY_SENTINEL_FILENAME: /opt/drupal/www-container-fs-ready
      SIMPLETEST_DB: $DB_URL
      XDEBUG_MODE: 'off'

  chrome:
    image: selenium/standalone-chrome:latest
