# Schema for the farmOS CSV import migration third party settings.
migrate_plus.migration.*.third_party.farm_import_csv:
  type: mapping
  label: 'farmOS CSV import settings'
  mapping:
    columns:
      type: sequence
      label: 'Columns'
      sequence:
        type: mapping
        label: 'Column'
        mapping:
          name:
            type: string
            label: 'Column name'
          description:
            type: text
            label: 'Column description'
    access:
      type: mapping
      label: 'Access control'
      mapping:
        permissions:
          type: sequence
          label: 'Permissions'
          sequence:
            type: string
            label: 'Permission'
