<?php

/**
 * @file
 * Contains farm_ui_guide.module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function farm_ui_guide_toolbar() {
  $user = \Drupal::currentUser();

  $items = [];
  $items['farm_guide'] = [
    '#cache' => [
      'contexts' => [
        'user.permissions',
      ],
    ],
  ];

  // Add user guide to the toolbar if the user has permission.
  if ($user->hasPermission('access farm user guide')) {
    $items['farm_guide'] += [
      '#type' => 'toolbar_item',
      'tab' => [
        '#type' => 'link',
        '#title' => t('User guide'),
        '#url' => Url::fromRoute('farm.guide'),
        '#attributes' => [
          'title' => t('User guide'),
          'class' => ['toolbar-icon', 'toolbar-icon-farm-guide'],
        ],
        '#attached' => [
          'library' => [
            'farm_ui_guide/toolbar',
          ],
        ],
      ],
      '#weight' => -10,
    ];
  }

  return $items;
}
