<?php
/**
 * @file
 * Code for the Farm Log: Observation feature.
 */

// Include Features code.
include_once 'farm_log_observation.features.inc';

/**
 * Implements hook_farm_record_types().
 */
function farm_log_observation_farm_record_types() {
  return array(
    'log' => array(
      'farm_observation' => array(
        'label' => t('Observation'),
        'label_plural' => t('Observations'),
        'view' => 'farm_log_observation',
        'areas' => TRUE,
        'weight' => -10,
      ),
    ),
  );
}
