# Schema for the configuration files of the organization module.
organization.type.*:
  type: config_entity
  label: 'Organization type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Type'
    description:
      type: text
      label: 'Description'
    workflow:
      type: string
      label: 'Workflow'
    new_revision:
      type: boolean
      label: 'Create new revision'

condition.plugin.organization_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string

action.configuration.organization_activate_action:
  type: action_configuration_default
  label: 'Configuration for the organization activate action'

action.configuration.organization_archive_action:
  type: action_configuration_default
  label: 'Configuration for the organization archive action'

action.configuration.organization_clone_action:
  type: action_configuration_default
  label: 'Configuration for the organization clone action'
